name:  Nightly beta build

on:
  schedule:
    - cron: "30 01 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: checkLastRun
        with:
          route: GET /repos/${{github.repository}}/actions/workflows/nightly.yml/runs?per_page=1&status=completed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo ${{github.repository}}
          echo "Last daily build: ${{ fromJson(steps.checkLastRun.outputs.data).workflow_runs[0].head_sha }}"

    outputs:
      last_sha: ${{ fromJson(steps.checkLastRun.outputs.data).workflow_runs[0].head_sha }}

  build:
    needs: [check]
    runs-on: ubuntu-latest
    if: needs.check.outputs.last_sha != github.sha
    steps:
      - run: |
          echo "Building new version"
          echo "Last daily build: ${{ needs.check.outputs.last_sha }}"
          echo "Current build: ${{ github.sha }}"

